# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datainfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_datainfo(object):
    def setupUi(self, datainfo):
        datainfo.setObjectName("datainfo")
        datainfo.resize(398, 293)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(datainfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(datainfo)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_info.setObjectName("verticalLayout_info")
        self.label_name = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.verticalLayout_info.addWidget(self.label_name)
        self.label_columns = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_columns.setFont(font)
        self.label_columns.setText("")
        self.label_columns.setObjectName("label_columns")
        self.verticalLayout_info.addWidget(self.label_columns)
        self.label_size = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_size.setFont(font)
        self.label_size.setText("")
        self.label_size.setObjectName("label_size")
        self.verticalLayout_info.addWidget(self.label_size)
        self.verticalLayout_3.addLayout(self.verticalLayout_info)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.widget = QtWidgets.QWidget(datainfo)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Load = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.btn_Load.setFont(font)
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout.addWidget(self.btn_Load)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(datainfo)
        QtCore.QMetaObject.connectSlotsByName(datainfo)

    def retranslateUi(self, datainfo):
        _translate = QtCore.QCoreApplication.translate
        datainfo.setWindowTitle(_translate("datainfo", "Form"))
        self.groupBox.setTitle(_translate("datainfo", "数据信息"))
        self.btn_Load.setText(_translate("datainfo", "Load"))
