# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessFilter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(350, 246)
        Filter.setMaximumSize(QtCore.QSize(350, 16777215))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Filter)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(Filter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cB_FilterType = QtWidgets.QComboBox(self.groupBox)
        self.cB_FilterType.setObjectName("cB_FilterType")
        self.cB_FilterType.addItem("")
        self.cB_FilterType.addItem("")
        self.verticalLayout.addWidget(self.cB_FilterType)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lE_WindowSize = QtWidgets.QLineEdit(self.groupBox_3)
        self.lE_WindowSize.setObjectName("lE_WindowSize")
        self.verticalLayout_2.addWidget(self.lE_WindowSize)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_4.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Load = QtWidgets.QPushButton(Filter)
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout.addWidget(self.btn_Load)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_Transfer = QtWidgets.QPushButton(Filter)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout.addWidget(self.btn_Transfer)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(Filter)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.verticalLayout_6.addLayout(self.verticalLayout_data)
        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(Filter)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(_translate("Filter", "Form"))
        self.groupBox.setTitle(_translate("Filter", "滤波选择"))
        self.cB_FilterType.setItemText(0, _translate("Filter", "中值滤波"))
        self.cB_FilterType.setItemText(1, _translate("Filter", "平滑滤波"))
        self.groupBox_3.setTitle(_translate("Filter", "参数设置"))
        self.lE_WindowSize.setPlaceholderText(_translate("Filter", "滤波窗口大小"))
        self.btn_Load.setText(_translate("Filter", "Load"))
        self.btn_Transfer.setText(_translate("Filter", "Transfer"))
        self.groupBox_2.setTitle(_translate("Filter", "数据"))
