# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessClean.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clean(object):
    def setupUi(self, Clean):
        Clean.setObjectName("Clean")
        Clean.resize(350, 246)
        Clean.setMaximumSize(QtCore.QSize(350, 16777215))

        # 整体水平布局（与滤波UI结构一致）
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Clean)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # 左侧垂直布局：清洗配置区域
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.widget = QtWidgets.QWidget(Clean)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # 清洗类型选择组
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")

        self.cB_CleanType = QtWidgets.QComboBox(self.groupBox)
        self.cB_CleanType.setObjectName("cB_CleanType")
        # 仅保留缺失值处理、异常值处理、一键清洗三个选项
        self.cB_CleanType.addItem("")
        self.cB_CleanType.addItem("")
        self.cB_CleanType.addItem("")
        self.verticalLayout.addWidget(self.cB_CleanType)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.verticalLayout_4.addWidget(self.widget)

        # 垂直占位符（撑开展示区域）
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)

        # 底部按钮水平布局：Load + Clean + Transfer
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.btn_Load = QtWidgets.QPushButton(Clean)
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout.addWidget(self.btn_Load)

        # 新增Clean按钮（核心清洗执行按钮）
        self.btn_Clean = QtWidgets.QPushButton(Clean)
        self.btn_Clean.setObjectName("btn_Clean")
        self.horizontalLayout.addWidget(self.btn_Clean)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.btn_Transfer = QtWidgets.QPushButton(Clean)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout.addWidget(self.btn_Transfer)

        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        # 右侧数据预览组（与滤波UI一致）
        self.groupBox_2 = QtWidgets.QGroupBox(Clean)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")

        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.verticalLayout_6.addLayout(self.verticalLayout_data)

        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(Clean)
        QtCore.QMetaObject.connectSlotsByName(Clean)

    def retranslateUi(self, Clean):
        _translate = QtCore.QCoreApplication.translate
        Clean.setWindowTitle(_translate("Clean", "Form"))

        # 清洗类型文本（删除重复值处理选项）
        self.groupBox.setTitle(_translate("Clean", "清洗类型"))
        self.cB_CleanType.setItemText(0, _translate("Clean", "缺失值处理(ffill)"))
        self.cB_CleanType.setItemText(1, _translate("Clean", "异常值处理(3σ法)"))
        self.cB_CleanType.setItemText(2, _translate("Clean", "一键清洗"))

        # 按钮文本
        self.btn_Load.setText(_translate("Clean", "Load"))
        self.btn_Clean.setText(_translate("Clean", "Clean"))  # 清洗执行按钮
        self.btn_Transfer.setText(_translate("Clean", "Transfer"))

        # 数据预览文本
        self.groupBox_2.setTitle(_translate("Clean", "数据"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Clean = QtWidgets.QWidget()
    ui = Ui_Clean()
    ui.setupUi(Clean)
    Clean.show()
    sys.exit(app.exec_())