# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlimport.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SQLimport(object):
    def setupUi(self, SQLimport):
        SQLimport.setObjectName("SQLimport")
        SQLimport.resize(240, 300)
        SQLimport.setMaximumSize(QtCore.QSize(240, 300))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SQLimport)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(SQLimport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lE_Server = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Server.setInputMask("")
        self.lE_Server.setText("")
        self.lE_Server.setObjectName("lE_Server")
        self.verticalLayout.addWidget(self.lE_Server)
        self.lE_Port = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Port.setReadOnly(False)
        self.lE_Port.setObjectName("lE_Port")
        self.verticalLayout.addWidget(self.lE_Port)
        self.lE_Database = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Database.setObjectName("lE_Database")
        self.verticalLayout.addWidget(self.lE_Database)
        self.lE_Username = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Username.setText("")
        self.lE_Username.setObjectName("lE_Username")
        self.verticalLayout.addWidget(self.lE_Username)
        self.lE_Password = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Password.setObjectName("lE_Password")
        self.verticalLayout.addWidget(self.lE_Password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_status.setMinimumSize(QtCore.QSize(23, 23))
        self.label_status.setMaximumSize(QtCore.QSize(23, 23))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_Connect = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Connect.setObjectName("btn_Connect")
        self.horizontalLayout.addWidget(self.btn_Connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(SQLimport)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cB_Tables = QtWidgets.QComboBox(self.groupBox)
        self.cB_Tables.setObjectName("cB_Tables")
        self.verticalLayout_2.addWidget(self.cB_Tables)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.btn_Transfer = QtWidgets.QPushButton(SQLimport)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.verticalLayout_3.addWidget(self.btn_Transfer)

        self.retranslateUi(SQLimport)
        QtCore.QMetaObject.connectSlotsByName(SQLimport)

    def retranslateUi(self, SQLimport):
        _translate = QtCore.QCoreApplication.translate
        SQLimport.setWindowTitle(_translate("SQLimport", "Form"))
        self.groupBox_2.setTitle(_translate("SQLimport", "Server"))
        self.lE_Server.setPlaceholderText(_translate("SQLimport", "Server"))
        self.lE_Port.setPlaceholderText(_translate("SQLimport", "Port"))
        self.lE_Database.setPlaceholderText(_translate("SQLimport", "Database"))
        self.lE_Username.setPlaceholderText(_translate("SQLimport", "Username"))
        self.lE_Password.setPlaceholderText(_translate("SQLimport", "Password"))
        self.btn_Connect.setText(_translate("SQLimport", "Connect"))
        self.groupBox.setTitle(_translate("SQLimport", "Tables"))
        self.btn_Transfer.setText(_translate("SQLimport", "Transfer"))
