# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tcp(object):
    def setupUi(self, tcp):
        tcp.setObjectName("tcp")
        tcp.resize(322, 227)
        self.verticalLayout = QtWidgets.QVBoxLayout(tcp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(tcp)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_IPaddress = QtWidgets.QLineEdit(tcp)
        self.le_IPaddress.setObjectName("le_IPaddress")
        self.horizontalLayout.addWidget(self.le_IPaddress)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(tcp)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_port = QtWidgets.QLineEdit(tcp)
        self.le_port.setObjectName("le_port")
        self.horizontalLayout_2.addWidget(self.le_port)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_listeningPort = QtWidgets.QPushButton(tcp)
        self.btn_listeningPort.setObjectName("btn_listeningPort")
        self.horizontalLayout_3.addWidget(self.btn_listeningPort)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(tcp)
        QtCore.QMetaObject.connectSlotsByName(tcp)

    def retranslateUi(self, tcp):
        _translate = QtCore.QCoreApplication.translate
        tcp.setWindowTitle(_translate("tcp", "Data Scope [TCP连接]"))
        self.label.setText(_translate("tcp", "IP地址："))
        self.le_IPaddress.setText(_translate("tcp", "172.27.208.1"))
        self.label_2.setText(_translate("tcp", "端口号："))
        self.le_port.setText(_translate("tcp", "5544"))
        self.btn_listeningPort.setText(_translate("tcp", "监听"))
