# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'niDAQmx.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NIDAQmx(object):
    def setupUi(self, NIDAQmx):
        NIDAQmx.setObjectName("NIDAQmx")
        NIDAQmx.resize(422, 219)
        self.verticalLayout = QtWidgets.QVBoxLayout(NIDAQmx)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lE_Channel = QtWidgets.QLineEdit(NIDAQmx)
        self.lE_Channel.setObjectName("lE_Channel")
        self.horizontalLayout_4.addWidget(self.lE_Channel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_CreateTask = QtWidgets.QPushButton(NIDAQmx)
        self.btn_CreateTask.setObjectName("btn_CreateTask")
        self.horizontalLayout.addWidget(self.btn_CreateTask)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_connectData = QtWidgets.QPushButton(NIDAQmx)
        self.btn_connectData.setObjectName("btn_connectData")
        self.horizontalLayout_2.addWidget(self.btn_connectData)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btn_CloseTask = QtWidgets.QPushButton(NIDAQmx)
        self.btn_CloseTask.setObjectName("btn_CloseTask")
        self.horizontalLayout_3.addWidget(self.btn_CloseTask)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(NIDAQmx)
        QtCore.QMetaObject.connectSlotsByName(NIDAQmx)

    def retranslateUi(self, NIDAQmx):
        _translate = QtCore.QCoreApplication.translate
        NIDAQmx.setWindowTitle(_translate("NIDAQmx", "Data Scope [NIDAQmx]"))
        self.lE_Channel.setText(_translate("NIDAQmx", "Dev2/ai0:3"))
        self.btn_CreateTask.setText(_translate("NIDAQmx", "创建任务"))
        self.btn_connectData.setText(_translate("NIDAQmx", "链接数据"))
        self.btn_CloseTask.setText(_translate("NIDAQmx", "关闭任务"))
