# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singlePlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_singlePlot(object):
    def setupUi(self, singlePlot):
        singlePlot.setObjectName("singlePlot")
        singlePlot.resize(521, 270)
        self.verticalLayout = QtWidgets.QVBoxLayout(singlePlot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Layout = QtWidgets.QHBoxLayout()
        self.Layout.setContentsMargins(9, 9, 9, 9)
        self.Layout.setObjectName("Layout")
        self.verticalLayout.addLayout(self.Layout)

        self.retranslateUi(singlePlot)
        QtCore.QMetaObject.connectSlotsByName(singlePlot)

    def retranslateUi(self, singlePlot):
        _translate = QtCore.QCoreApplication.translate
        singlePlot.setWindowTitle(_translate("singlePlot", "Data Scope [钻压]"))
