# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SqlConnect(object):
    def setupUi(self, SqlConnect):
        SqlConnect.setObjectName("SqlConnect")
        SqlConnect.resize(260, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SqlConnect.sizePolicy().hasHeightForWidth())
        SqlConnect.setSizePolicy(sizePolicy)
        SqlConnect.setMinimumSize(QtCore.QSize(260, 200))
        SqlConnect.setMaximumSize(QtCore.QSize(260, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SqlConnect)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(SqlConnect)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lE_Server = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Server.setInputMask("")
        self.lE_Server.setText("")
        self.lE_Server.setObjectName("lE_Server")
        self.verticalLayout.addWidget(self.lE_Server)
        self.lE_Port = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Port.setReadOnly(False)
        self.lE_Port.setObjectName("lE_Port")
        self.verticalLayout.addWidget(self.lE_Port)
        self.lE_Database = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Database.setObjectName("lE_Database")
        self.verticalLayout.addWidget(self.lE_Database)
        self.lE_Username = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Username.setText("")
        self.lE_Username.setObjectName("lE_Username")
        self.verticalLayout.addWidget(self.lE_Username)
        self.lE_Password = QtWidgets.QLineEdit(self.groupBox_2)
        self.lE_Password.setObjectName("lE_Password")
        self.verticalLayout.addWidget(self.lE_Password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_status = QtWidgets.QLabel(self.groupBox_2)
        self.label_status.setMinimumSize(QtCore.QSize(23, 23))
        self.label_status.setMaximumSize(QtCore.QSize(23, 23))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_Connect = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Connect.setObjectName("btn_Connect")
        self.horizontalLayout.addWidget(self.btn_Connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(SqlConnect)
        QtCore.QMetaObject.connectSlotsByName(SqlConnect)

    def retranslateUi(self, SqlConnect):
        _translate = QtCore.QCoreApplication.translate
        SqlConnect.setWindowTitle(_translate("SqlConnect", "Form"))
        self.groupBox_2.setTitle(_translate("SqlConnect", "Server"))
        self.lE_Server.setPlaceholderText(_translate("SqlConnect", "Server"))
        self.lE_Port.setPlaceholderText(_translate("SqlConnect", "Port"))
        self.lE_Database.setPlaceholderText(_translate("SqlConnect", "Database"))
        self.lE_Username.setPlaceholderText(_translate("SqlConnect", "Username"))
        self.lE_Password.setPlaceholderText(_translate("SqlConnect", "Password"))
        self.btn_Connect.setText(_translate("SqlConnect", "Connect"))
