# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DisplayLinePlot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinePlot(object):
    def setupUi(self, LinePlot):
        LinePlot.setObjectName("LinePlot")
        LinePlot.resize(800, 520)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(LinePlot)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(LinePlot)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        # ------------------- 左侧Data组框修改 -------------------
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        # 1. 设置左侧部件的固定宽度（缩短左侧，且禁止拉伸）
        self.groupBox_2.setFixedWidth(150)  # 可根据需求调整宽度值
        # 也可通过设置最小/最大宽度实现固定：
        # self.groupBox_2.setMinimumWidth(150)
        # self.groupBox_2.setMaximumWidth(150)

        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.verticalLayout.addLayout(self.verticalLayout_data)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cB_type = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.cB_type.setFont(font)
        self.cB_type.setObjectName("cB_type")
        self.cB_type.addItem("")
        self.cB_type.addItem("")
        self.cB_type.addItem("")
        self.horizontalLayout.addWidget(self.cB_type)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_Clear = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Clear.setObjectName("btn_Clear")
        self.verticalLayout.addWidget(self.btn_Clear)
        self.btn_Load = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Load.setObjectName("btn_Load")
        self.verticalLayout.addWidget(self.btn_Load)

        # ------------------- 右侧绘图区组框修改 -------------------
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_plot = QtWidgets.QVBoxLayout()
        self.verticalLayout_plot.setObjectName("verticalLayout_plot")
        self.verticalLayout_2.addLayout(self.verticalLayout_plot)

        # ------------------- Splitter拉伸因子设置 -------------------
        # 设置拉伸因子：索引0（左侧）为0，索引1（右侧）为1
        # 表示窗体拉伸时，仅右侧分配拉伸空间
        self.splitter.setStretchFactor(0, 0)
        self.splitter.setStretchFactor(1, 1)

        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(LinePlot)
        QtCore.QMetaObject.connectSlotsByName(LinePlot)

    def retranslateUi(self, LinePlot):
        _translate = QtCore.QCoreApplication.translate
        LinePlot.setWindowTitle(_translate("LinePlot", "Form"))
        self.groupBox_2.setTitle(_translate("LinePlot", "Data"))
        self.label.setText(_translate("LinePlot", "类型"))
        self.cB_type.setItemText(0, _translate("LinePlot", "1to1"))
        self.cB_type.setItemText(1, _translate("LinePlot", "2to1"))
        self.cB_type.setItemText(2, _translate("LinePlot", "3to1"))
        self.btn_Clear.setText(_translate("LinePlot", "Clear"))
        self.btn_Load.setText(_translate("LinePlot", "Load"))
        self.groupBox.setTitle(_translate("LinePlot", "绘图区"))