# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessResample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Resample(object):
    def setupUi(self, Resample):
        Resample.setObjectName("Resample")
        Resample.resize(550, 320)  # 加宽适配新参数
        Resample.setMaximumSize(QtCore.QSize(550, 16777215))  # 最大宽度限制，高度自适应
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Resample)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # 左侧：参数设置区域
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(Resample)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # 处理类型选择组
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cB_ProcessType = QtWidgets.QComboBox(self.groupBox)
        self.cB_ProcessType.setObjectName("cB_ProcessType")
        self.verticalLayout.addWidget(self.cB_ProcessType)
        self.verticalLayout_3.addWidget(self.groupBox)

        # 降采样参数组
        self.groupBox_DownSample = QtWidgets.QGroupBox(self.widget)
        self.groupBox_DownSample.setObjectName("groupBox_DownSample")
        self.horizontalLayout_Down = QtWidgets.QHBoxLayout(self.groupBox_DownSample)
        self.horizontalLayout_Down.setObjectName("horizontalLayout_Down")
        self.label_Down = QtWidgets.QLabel(self.groupBox_DownSample)
        self.label_Down.setObjectName("label_Down")
        self.horizontalLayout_Down.addWidget(self.label_Down)
        self.cB_DownSample = QtWidgets.QComboBox(self.groupBox_DownSample)
        self.cB_DownSample.setObjectName("cB_DownSample")
        self.horizontalLayout_Down.addWidget(self.cB_DownSample)
        self.verticalLayout_3.addWidget(self.groupBox_DownSample)

        # 升采样参数组
        self.groupBox_UpSample = QtWidgets.QGroupBox(self.widget)
        self.groupBox_UpSample.setObjectName("groupBox_UpSample")
        self.horizontalLayout_Up = QtWidgets.QHBoxLayout(self.groupBox_UpSample)
        self.horizontalLayout_Up.setObjectName("horizontalLayout_Up")
        self.label_Up = QtWidgets.QLabel(self.groupBox_UpSample)
        self.label_Up.setObjectName("label_Up")
        self.horizontalLayout_Up.addWidget(self.label_Up)
        self.cB_UpSample = QtWidgets.QComboBox(self.groupBox_UpSample)
        self.cB_UpSample.setObjectName("cB_UpSample")
        self.horizontalLayout_Up.addWidget(self.cB_UpSample)
        self.verticalLayout_3.addWidget(self.groupBox_UpSample)

        # 时间对齐参数组
        self.groupBox_Align = QtWidgets.QGroupBox(self.widget)
        self.groupBox_Align.setObjectName("groupBox_Align")
        self.verticalLayout_Align = QtWidgets.QVBoxLayout(self.groupBox_Align)
        self.verticalLayout_Align.setObjectName("verticalLayout_Align")
        self.label_Align = QtWidgets.QLabel(self.groupBox_Align)
        self.label_Align.setObjectName("label_Align")
        self.verticalLayout_Align.addWidget(self.label_Align)
        self.verticalLayout_3.addWidget(self.groupBox_Align)

        self.verticalLayout_4.addWidget(self.widget)

        # 垂直 spacer，让按钮靠下
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)

        # 按钮组：水平排列（加载数据组一 → 加载数据组二 → 空白间隔 → 处理并传递）
        self.horizontalLayout_btn = QtWidgets.QHBoxLayout()  # 外层水平布局
        self.horizontalLayout_btn.setObjectName("horizontalLayout_btn")
        self.horizontalLayout_btn.setSpacing(15)  # 按钮之间的基础间距

        # 加载数据组一
        self.btn_Load = QtWidgets.QPushButton(Resample)
        self.btn_Load.setObjectName("btn_Load")
        self.btn_Load.setMinimumWidth(100)  # 固定最小宽度，保证文本显示完整
        self.horizontalLayout_btn.addWidget(self.btn_Load)

        # 加载数据组二（放在中间）
        self.btn_Load2 = QtWidgets.QPushButton(Resample)
        self.btn_Load2.setObjectName("btn_Load2")
        self.btn_Load2.setMinimumWidth(100)  # 固定最小宽度
        self.horizontalLayout_btn.addWidget(self.btn_Load2)

        # 水平 spacer：占满剩余空间，让处理并传递按钮靠右
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_btn.addItem(spacerItem1)

        # 处理并传递
        self.btn_Transfer = QtWidgets.QPushButton(Resample)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.btn_Transfer.setMinimumWidth(100)  # 固定最小宽度
        self.horizontalLayout_btn.addWidget(self.btn_Transfer)

        self.verticalLayout_4.addLayout(self.horizontalLayout_btn)

        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        # 右侧：数据列显示区域
        self.groupBox_2 = QtWidgets.QGroupBox(Resample)
        self.groupBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.verticalLayout_6.addLayout(self.verticalLayout_data)

        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(Resample)
        QtCore.QMetaObject.connectSlotsByName(Resample)

    def retranslateUi(self, Resample):
        _translate = QtCore.QCoreApplication.translate
        Resample.setWindowTitle(_translate("Resample", "数据重采样与时间对齐"))

        # 处理类型
        self.groupBox.setTitle(_translate("Resample", "处理类型"))
        self.cB_ProcessType.addItems([
            _translate("Resample", "降采样"),
            _translate("Resample", "升采样"),
            _translate("Resample", "时间对齐")
        ])

        # 降采样参数
        self.groupBox_DownSample.setTitle(_translate("Resample", "降采样参数"))
        self.label_Down.setText(_translate("Resample", "时间间隔："))
        self.cB_DownSample.addItems([
            _translate("Resample", "30s"),
            _translate("Resample", "1min"),
            _translate("Resample", "5min")
        ])

        # 升采样参数
        self.groupBox_UpSample.setTitle(_translate("Resample", "升采样参数"))
        self.label_Up.setText(_translate("Resample", "采样频率："))
        self.cB_UpSample.addItems([
            _translate("Resample", "1200Hz"),
            _translate("Resample", "1000Hz"),
            _translate("Resample", "800Hz"),
            _translate("Resample", "400Hz"),
            _translate("Resample", "200Hz")
        ])

        # 时间对齐参数
        self.groupBox_Align.setTitle(_translate("Resample", "时间对齐说明"))
        self.label_Align.setText(_translate("Resample", "请先加载两个表格数据，自动对齐时间轴"))

        # 按钮
        self.btn_Load.setText(_translate("Resample", "加载数据组一"))
        self.btn_Load2.setText(_translate("Resample", "加载数据组二"))
        self.btn_Transfer.setText(_translate("Resample", "Transfer"))

        # 数据列显示
        self.groupBox_2.setTitle(_translate("Resample", "数据列信息"))
