# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveData(object):
    def setupUi(self, saveData):
        saveData.setObjectName("saveData")
        saveData.resize(350, 250)  # 适当放大窗口，适配新控件
        saveData.setMinimumSize(QtCore.QSize(350, 250))
        saveData.setMaximumSize(QtCore.QSize(500, 300))  # 放宽最大尺寸限制
        self.verticalLayout = QtWidgets.QVBoxLayout(saveData)
        self.verticalLayout.setObjectName("verticalLayout")

        # 1. 添加数据信息组框（用于显示加载的数据信息）
        self.groupBox_Info = QtWidgets.QGroupBox(saveData)
        self.groupBox_Info.setObjectName("groupBox_Info")
        self.verticalLayout_Info = QtWidgets.QVBoxLayout(self.groupBox_Info)
        self.verticalLayout_Info.setObjectName("verticalLayout_Info")

        # 数据信息标签（核心新增控件）
        self.label_info = QtWidgets.QLabel(self.groupBox_Info)
        self.label_info.setObjectName("label_info")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)  # 居中显示
        self.label_info.setStyleSheet("color: #333333; font-size: 12px;")  # 样式优化
        self.verticalLayout_Info.addWidget(self.label_info)
        self.verticalLayout.addWidget(self.groupBox_Info)

        # 2. 原有保存文件组框
        self.groupBox = QtWidgets.QGroupBox(saveData)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # 可选：添加文件格式选择下拉框（增强功能）
        self.horizontalLayout_Format = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Format.setObjectName("horizontalLayout_Format")
        self.label_Format = QtWidgets.QLabel(self.groupBox)
        self.label_Format.setObjectName("label_Format")
        self.horizontalLayout_Format.addWidget(self.label_Format)
        self.combo_Format = QtWidgets.QComboBox(self.groupBox)
        self.combo_Format.setObjectName("combo_Format")
        self.combo_Format.addItem("CSV (*.csv)")
        self.combo_Format.addItem("Excel (*.xlsx)")  # 后续可扩展Excel保存功能
        self.horizontalLayout_Format.addWidget(self.combo_Format)
        self.verticalLayout_2.addLayout(self.horizontalLayout_Format)

        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        # 保存按钮布局
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_Save = QtWidgets.QPushButton(self.groupBox)
        self.btn_Save.setObjectName("btn_Save")
        self.btn_Save.setMinimumSize(QtCore.QSize(80, 30))  # 放大按钮
        self.horizontalLayout.addWidget(self.btn_Save)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        # 进度条（原有）
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)

        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox)

        # 3. 加载按钮布局（原有）
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Load = QtWidgets.QPushButton(saveData)
        self.btn_Load.setObjectName("btn_Load")
        self.btn_Load.setMinimumSize(QtCore.QSize(80, 30))  # 放大按钮
        self.horizontalLayout_2.addWidget(self.btn_Load)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(saveData)
        QtCore.QMetaObject.connectSlotsByName(saveData)

    def retranslateUi(self, saveData):
        _translate = QtCore.QCoreApplication.translate
        saveData.setWindowTitle(_translate("saveData", "数据保存"))
        # 数据信息组框文本
        self.groupBox_Info.setTitle(_translate("saveData", "数据信息"))
        self.label_info.setText(_translate("saveData", "未加载数据"))
        # 文件格式标签文本

        self.label_Format.setText(_translate("saveData", "文件格式："))
        # 保存文件组框文本
        self.groupBox.setTitle(_translate("saveData", "保存设置"))
        self.btn_Save.setText(_translate("saveData", "保存"))
        self.btn_Load.setText(_translate("saveData", "Load"))