# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlDownload.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sqlDownload(object):
    def setupUi(self, sqlDownload):
        sqlDownload.setObjectName("sqlDownload")
        sqlDownload.resize(477, 80)
        sqlDownload.setMaximumSize(QtCore.QSize(16777215, 80))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(sqlDownload)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(sqlDownload)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cB_Tables = QtWidgets.QComboBox(self.groupBox)
        self.cB_Tables.setObjectName("cB_Tables")
        self.horizontalLayout.addWidget(self.cB_Tables)
        self.btn_ShowTables = QtWidgets.QPushButton(self.groupBox)
        self.btn_ShowTables.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_ShowTables.setObjectName("btn_ShowTables")
        self.horizontalLayout.addWidget(self.btn_ShowTables)
        self.btn_Download = QtWidgets.QPushButton(self.groupBox)
        self.btn_Download.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btn_Download.setObjectName("btn_Download")
        self.horizontalLayout.addWidget(self.btn_Download)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(sqlDownload)
        QtCore.QMetaObject.connectSlotsByName(sqlDownload)

    def retranslateUi(self, sqlDownload):
        _translate = QtCore.QCoreApplication.translate
        sqlDownload.setWindowTitle(_translate("sqlDownload", "Form"))
        self.groupBox.setTitle(_translate("sqlDownload", "表"))
        self.btn_ShowTables.setText(_translate("sqlDownload", "刷新"))
        self.btn_Download.setText(_translate("sqlDownload", "下载"))
