# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csvImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSVImport(object):
    def setupUi(self, CSVImport):
        CSVImport.setObjectName("CSVImport")
        CSVImport.resize(752, 498)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CSVImport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CSVImport)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cB_FilePath = QtWidgets.QComboBox(CSVImport)
        self.cB_FilePath.setMinimumSize(QtCore.QSize(300, 0))
        self.cB_FilePath.setObjectName("cB_FilePath")
        self.horizontalLayout.addWidget(self.cB_FilePath)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.btn_OpenFile = QtWidgets.QPushButton(CSVImport)
        self.btn_OpenFile.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_OpenFile.setObjectName("btn_OpenFile")
        self.horizontalLayout_2.addWidget(self.btn_OpenFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(CSVImport)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tV_DataView = QtWidgets.QTableView(self.groupBox)
        self.tV_DataView.setObjectName("tV_DataView")
        self.verticalLayout.addWidget(self.tV_DataView)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cB_count = QtWidgets.QComboBox(CSVImport)
        self.cB_count.setObjectName("cB_count")
        self.horizontalLayout_3.addWidget(self.cB_count)
        self.btn_delete = QtWidgets.QPushButton(CSVImport)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_3.addWidget(self.btn_delete)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(CSVImport)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.btn_Transfer = QtWidgets.QPushButton(CSVImport)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout_3.addWidget(self.btn_Transfer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(CSVImport)
        QtCore.QMetaObject.connectSlotsByName(CSVImport)

    def retranslateUi(self, CSVImport):
        _translate = QtCore.QCoreApplication.translate
        CSVImport.setWindowTitle(_translate("CSVImport", "Form"))
        self.label.setText(_translate("CSVImport", "File："))
        self.btn_OpenFile.setText(_translate("CSVImport", "Open"))
        self.groupBox.setTitle(_translate("CSVImport", "Data"))
        self.btn_delete.setText(_translate("CSVImport", "Delete"))
        self.btn_Transfer.setText(_translate("CSVImport", "Transfer"))
