# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oilFuncTimeConv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OilFuncTimeConv(object):
    def setupUi(self, OilFuncTimeConv):
        OilFuncTimeConv.setObjectName("OilFuncTimeConv")
        OilFuncTimeConv.resize(800, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(OilFuncTimeConv)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 左侧参数配置分组框
        self.groupBox = QtWidgets.QGroupBox(OilFuncTimeConv)
        self.groupBox.setTitle("时间转换参数配置")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # 时间列选择标签和下拉框
        self.label_time_col = QtWidgets.QLabel(self.groupBox)
        self.label_time_col.setObjectName("label_time_col")
        self.verticalLayout_2.addWidget(self.label_time_col)

        self.combo_time_col = QtWidgets.QComboBox(self.groupBox)
        self.combo_time_col.setObjectName("combo_time_col")
        self.verticalLayout_2.addWidget(self.combo_time_col)

        # 输入格式标签和输入框（改为只读，显示自动检测）
        self.label_input_format = QtWidgets.QLabel(self.groupBox)
        self.label_input_format.setObjectName("label_input_format")
        self.verticalLayout_2.addWidget(self.label_input_format)

        self.line_input_format = QtWidgets.QLineEdit(self.groupBox)
        # 设置为只读，显示自动检测提示
        self.line_input_format.setReadOnly(True)
        self.line_input_format.setText("自动检测时间格式")
        self.line_input_format.setStyleSheet("color: gray;")
        self.line_input_format.setObjectName("line_input_format")
        self.verticalLayout_2.addWidget(self.line_input_format)

        # 输出格式标签和输入框（预设格式）
        self.label_output_format = QtWidgets.QLabel(self.groupBox)
        self.label_output_format.setObjectName("label_output_format")
        self.verticalLayout_2.addWidget(self.label_output_format)

        self.line_output_format = QtWidgets.QLineEdit(self.groupBox)
        # 预设输出格式为2000/1/1 0:00:23对应的格式字符串
        self.line_output_format.setText("%Y/%m/%d %H:%M:%S")
        self.line_output_format.setPlaceholderText("固定格式：2000/1/1 0:00:23")
        self.line_output_format.setObjectName("line_output_format")
        self.verticalLayout_2.addWidget(self.line_output_format)

        # 加载和转换按钮
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.btn_Load = QtWidgets.QPushButton(self.groupBox)
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout_3.addWidget(self.btn_Load)

        self.btn_Transfer = QtWidgets.QPushButton(self.groupBox)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout_3.addWidget(self.btn_Transfer)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        # 占位符（拉伸用）
        self.spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(self.spacerItem)

        self.horizontalLayout.addWidget(self.groupBox, stretch=1)  # 左侧占1份

        # 右侧直接作为数据展示区域（移除原有的列选择分组框）
        self.data_display_widget = QtWidgets.QWidget(OilFuncTimeConv)
        self.data_display_widget.setObjectName("data_display_widget")
        self.verticalLayout_data = QtWidgets.QVBoxLayout(self.data_display_widget)
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.horizontalLayout.addWidget(self.data_display_widget, stretch=3)  # 右侧占3份，更宽的展示区域

        self.retranslateUi(OilFuncTimeConv)
        QtCore.QMetaObject.connectSlotsByName(OilFuncTimeConv)

    def retranslateUi(self, OilFuncTimeConv):
        _translate = QtCore.QCoreApplication.translate
        OilFuncTimeConv.setWindowTitle(_translate("OilFuncTimeConv", "时间转换"))
        self.label_time_col.setText(_translate("OilFuncTimeConv", "时间列："))
        self.label_input_format.setText(_translate("OilFuncTimeConv", "输入时间格式（自动检测）："))
        self.label_output_format.setText(_translate("OilFuncTimeConv", "输出时间格式（固定）："))
        self.btn_Load.setText(_translate("OilFuncTimeConv", "Load"))
        self.btn_Transfer.setText(_translate("OilFuncTimeConv", "Convert"))