# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oilFuncStandardization.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Standardization(object):
    def setupUi(self, Standardization):
        Standardization.setObjectName("Standardization")
        Standardization.resize(506, 534)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Standardization)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(Standardization)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.widget)
        self.btn_Cal = QtWidgets.QPushButton(Standardization)
        self.btn_Cal.setObjectName("btn_Cal")
        self.verticalLayout_3.addWidget(self.btn_Cal)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Load = QtWidgets.QPushButton(Standardization)
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout.addWidget(self.btn_Load)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_Transfer = QtWidgets.QPushButton(Standardization)
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout.addWidget(self.btn_Transfer)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Standardization)
        QtCore.QMetaObject.connectSlotsByName(Standardization)

    def retranslateUi(self, Standardization):
        _translate = QtCore.QCoreApplication.translate
        Standardization.setWindowTitle(_translate("Standardization", "Form"))
        self.btn_Cal.setText(_translate("Standardization", "Calculate"))
        self.btn_Load.setText(_translate("Standardization", "Load"))
        self.btn_Transfer.setText(_translate("Standardization", "Transfer"))
