# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcessTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_time(object):
    def setupUi(self, time):
        time.setObjectName("time")
        time.resize(800, 520)  # 保持原始尺寸
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(time)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        # 垂直分割器：上半部分（水平分割：参数+绘图）、下半部分（表格）
        self.splitter_main = QtWidgets.QSplitter(time)
        self.splitter_main.setOrientation(QtCore.Qt.Vertical)
        self.splitter_main.setObjectName("splitter_main")

        # --------------------------
        # 上半部分：水平分割器（左侧参数区 + 右侧绘图区）
        # --------------------------
        self.splitter_h = QtWidgets.QSplitter(self.splitter_main)
        self.splitter_h.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_h.setObjectName("splitter_h")

        # 左侧参数分组框（固定宽度）
        self.groupBox = QtWidgets.QGroupBox(self.splitter_h)
        self.groupBox.setMinimumSize(QtCore.QSize(180, 0))  # 微调左侧宽度，适配长按钮
        self.groupBox.setMaximumSize(QtCore.QSize(180, 16777215))  # 固定宽度（从150调整为180，容纳长按钮）
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # 数据列选择区
        self.verticalLayout_data = QtWidgets.QVBoxLayout()
        self.verticalLayout_data.setObjectName("verticalLayout_data")
        self.verticalLayout_2.addLayout(self.verticalLayout_data)

        # 伸缩项
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        # --------------------------
        # 按时间显示按钮（核心绘图按钮）
        # --------------------------
        self.btn_Show_Time = QtWidgets.QPushButton(self.groupBox)
        self.btn_Show_Time.setMinimumWidth(150)  # 与其他按钮宽度一致
        self.btn_Show_Time.setObjectName("btn_Show_Time")
        self.verticalLayout_2.addWidget(self.btn_Show_Time)

        # --------------------------
        # 按日期显示按钮（核心绘图按钮）
        # --------------------------
        self.btn_Show_Date = QtWidgets.QPushButton(self.groupBox)
        self.btn_Show_Date.setMinimumWidth(150)  # 与其他按钮宽度一致
        self.btn_Show_Date.setObjectName("btn_Show_Date")
        self.verticalLayout_2.addWidget(self.btn_Show_Date)

        # 计算选区特征按钮（延长宽度）
        self.btn_Calculate = QtWidgets.QPushButton(self.groupBox)
        self.btn_Calculate.setMinimumWidth(150)  # 设置最小宽度，保证文字完整显示
        self.btn_Calculate.setObjectName("btn_Calculate")
        self.verticalLayout_2.addWidget(self.btn_Calculate)

        # 批量特征设置分组框
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")

        # 特征类型下拉框
        self.cB_Features = QtWidgets.QComboBox(self.groupBox_4)
        self.cB_Features.setObjectName("cB_Features")
        self.verticalLayout.addWidget(self.cB_Features)

        # 采样数输入框
        self.lE_Sample = QtWidgets.QLineEdit(self.groupBox_4)
        self.lE_Sample.setPlaceholderText("采样率")
        self.lE_Sample.setObjectName("lE_Sample")
        self.verticalLayout.addWidget(self.lE_Sample)

        # 批量计算特征按钮（延长宽度）
        self.btn_AllFeaturesCalculate = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_AllFeaturesCalculate.setMinimumWidth(150)  # 设置最小宽度，保证文字完整显示
        self.btn_AllFeaturesCalculate.setObjectName("btn_AllFeaturesCalculate")
        self.verticalLayout.addWidget(self.btn_AllFeaturesCalculate)

        self.verticalLayout_2.addWidget(self.groupBox_4)

        # 右侧绘图区分组框
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_h)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # --------------------------
        # 新增：时间范围显示标签（和频域一致）
        # --------------------------
        self.label_time_range = QtWidgets.QLabel(self.groupBox_2)
        self.label_time_range.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_range.setMinimumHeight(30)
        self.label_time_range.setStyleSheet("""
            QLabel {
                font-size: 12px;
                font-weight: bold;
                color: #333333;
                padding: 5px;
                border: 1px solid #cccccc;
                border-radius: 4px;
                background-color: #f8f8f8;
            }
        """)
        self.label_time_range.setObjectName("label_time_range")
        self.verticalLayout_4.addWidget(self.label_time_range)

        # 绘图布局
        self.verticalLayout_draw = QtWidgets.QVBoxLayout()
        self.verticalLayout_draw.setObjectName("verticalLayout_draw")
        self.verticalLayout_4.addLayout(self.verticalLayout_draw)

        # 设置水平分割器的拉伸因子：左侧固定，右侧拉伸
        self.splitter_h.setStretchFactor(0, 0)
        self.splitter_h.setStretchFactor(1, 1)

        # --------------------------
        # 下半部分：特征表格分组框
        # --------------------------
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_main)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        # 特征表格
        self.tV_TimeFeatures = QtWidgets.QTableView(self.groupBox_3)
        self.tV_TimeFeatures.setObjectName("tV_TimeFeatures")
        self.verticalLayout_5.addWidget(self.tV_TimeFeatures)

        # 设置垂直分割器的拉伸因子
        self.splitter_main.setStretchFactor(0, 1)
        self.splitter_main.setStretchFactor(1, 0)

        self.verticalLayout_7.addWidget(self.splitter_main)

        # --------------------------
        # 底部按钮栏（提升Load和Transfer按钮高度）
        # --------------------------
        self.widget = QtWidgets.QWidget(time)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))  # 微调按钮栏高度
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 加载按钮（提升高度）
        self.btn_Load = QtWidgets.QPushButton(self.widget)
        self.btn_Load.setMinimumHeight(35)  # 设置最小高度，提升按钮高度
        self.btn_Load.setObjectName("btn_Load")
        self.horizontalLayout.addWidget(self.btn_Load)

        # 伸缩项
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        # 传输按钮（提升高度）
        self.btn_Transfer = QtWidgets.QPushButton(self.widget)
        self.btn_Transfer.setMinimumHeight(35)  # 设置最小高度，提升按钮高度
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.horizontalLayout.addWidget(self.btn_Transfer)

        self.verticalLayout_7.addWidget(self.widget)

        self.retranslateUi(time)
        QtCore.QMetaObject.connectSlotsByName(time)

    def retranslateUi(self, time):
        _translate = QtCore.QCoreApplication.translate
        time.setWindowTitle(_translate("time", "Form"))
        self.groupBox.setTitle(_translate("time", "数据"))
        # 仅保留新增按钮的文本
        self.btn_Show_Time.setText(_translate("time", "按时间显示"))
        self.btn_Show_Date.setText(_translate("time", "按日期显示"))
        self.btn_Calculate.setText(_translate("time", "计算选区时域特征"))
        self.groupBox_4.setTitle(_translate("time", "设置特征输出"))
        self.btn_AllFeaturesCalculate.setText(_translate("time", "计算时域特征输出"))
        self.groupBox_2.setTitle(_translate("time", "绘图区"))
        # 新增：时间标签默认文本
        self.label_time_range.setText(_translate("time", "当前选中时间：无"))
        self.groupBox_3.setTitle(_translate("time", "时域特征值"))
        self.btn_Load.setText(_translate("time", "Load"))
        self.btn_Transfer.setText(_translate("time", "Transfer"))