# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motionStatusDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_motionStatusDisplay(object):
    def setupUi(self, motionStatusDisplay):
        motionStatusDisplay.setObjectName("motionStatusDisplay")
        motionStatusDisplay.resize(622, 510)
        self.verticalLayout = QtWidgets.QVBoxLayout(motionStatusDisplay)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(motionStatusDisplay)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(motionStatusDisplay)
        QtCore.QMetaObject.connectSlotsByName(motionStatusDisplay)

    def retranslateUi(self, motionStatusDisplay):
        _translate = QtCore.QCoreApplication.translate
        motionStatusDisplay.setWindowTitle(_translate("motionStatusDisplay", "Drill Syar - Data Scope [运动状态显示]"))
